# Generated by Django 6.0.3 on 2026-04-08 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Finance', '금융'), ('Housing', '주거'), ('Welfare', '복지'), ('Employment', '고용/취업'), ('Legal', '법률/상담'), ('Youth', '청년특화'), ('Institution', '제도/민원')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('age_max', models.IntegerField(blank=True, null=True)),
                ('age_min', models.IntegerField(blank=True, default=0, null=True)),
                ('income_limit', models.IntegerField(blank=True, help_text='합산 연소득 제한 (만원)', null=True)),
                ('asset_limit', models.IntegerField(blank=True, help_text='보유 자산 제한 (만원)', null=True)),
                ('requires_kids', models.BooleanField(default=False)),
                ('marital_status', models.JSONField(blank=True, default=list, help_text="['single', 'newly', 'expecting'] 등")),
                ('is_non_homeowner_only', models.BooleanField(default=False, help_text='무주택자 전용 여부')),
                ('employment_types', models.JSONField(blank=True, default=list, help_text="['employee', 'business', 'unemployed', 'freelancer'] 등")),
                ('is_low_income_only', models.BooleanField(default=False, help_text='기초생활수급자/차상위 전용 여부')),
                ('is_disabled_only', models.BooleanField(default=False, help_text='장애인 전용 여부')),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='평균 금리 (%)', max_digits=4, null=True)),
                ('max_limit', models.IntegerField(blank=True, help_text='최대 한도/수혜액 (만원)', null=True)),
                ('benefit_type', models.CharField(blank=True, choices=[('Loan', '대출'), ('Grant', '보조금'), ('Savings', '저축')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '정책',
                'verbose_name_plural': '정책 목록',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='이름/식별자')),
                ('age', models.IntegerField(default=29, verbose_name='만 나이')),
                ('income', models.IntegerField(default=5000, verbose_name='연소득 (만원)')),
                ('region', models.CharField(default='seoul', max_length=50, verbose_name='지역')),
                ('is_non_homeowner', models.BooleanField(default=True, verbose_name='무주택 여부')),
                ('personal_api_key', models.CharField(blank=True, help_text='사용자 전용 API 키', max_length=100, null=True)),
                ('ai_persona', models.TextField(blank=True, help_text='AI 비서의 성격', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필 목록',
            },
        ),
    ]
