# Generated by Django 6.0.3 on 2026-04-07 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=29, verbose_name='연령')),
                ('region', models.CharField(choices=[('Seoul', '서울'), ('Gyeonggi', '경기'), ('Incheon', '인천'), ('Busan', '부산'), ('Other', '기타')], default='Seoul', max_length=20, verbose_name='거주지')),
                ('marital_status', models.CharField(choices=[('Single', '미혼'), ('Engaged', '예비신혼'), ('Married', '신혼부부(7년 이내)'), ('Other', '기타')], default='Single', max_length=20, verbose_name='혼인상태')),
                ('kids_count', models.IntegerField(default=0, verbose_name='자녀 수')),
                ('is_pregnant', models.BooleanField(default=False, verbose_name='임신여부')),
                ('total_income', models.IntegerField(help_text='가구 합산 연소득 (단위: 만원)', verbose_name='연소득')),
                ('assets', models.IntegerField(help_text='가구 총 자산 (단위: 만원)', verbose_name='보유 자산')),
                ('debt', models.IntegerField(default=0, help_text='현재 부채 규모 (단위: 만원)', verbose_name='부채 규모')),
                ('subscription_count', models.IntegerField(default=24, verbose_name='청약통장 납입 횟수')),
                ('subscription_amount', models.IntegerField(default=240, help_text='청약 총 불입 금액 (단위: 만원)', verbose_name='청약 총액')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='진단 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('user', models.ForeignKey(help_text='정보를 입력한 사용자 계정', on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 진단 기록',
                'verbose_name_plural': '사용자 진단 기록 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
