# Generated by Django 6.0.3 on 2026-04-07 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_road', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiagnostic',
            name='user',
            field=models.ForeignKey(blank=True, help_text='정보를 입력한 사용자 계정 (익명 가능)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to=settings.AUTH_USER_MODEL),
        ),
    ]
