# Generated by Django 6.0.3 on 2026-04-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_road', '0002_alter_userdiagnostic_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True, verbose_name='상품ID')),
                ('title', models.CharField(max_length=255, verbose_name='상품명')),
                ('bank_nm', models.CharField(max_length=100, verbose_name='금융기관')),
                ('category', models.CharField(max_length=100, verbose_name='상품구분')),
                ('base_rate', models.FloatField(default=0.0, verbose_name='기본금리')),
                ('max_rate', models.FloatField(default=0.0, verbose_name='우대금리포함')),
                ('limit_amt', models.BigIntegerField(default=0, verbose_name='대출한도(원)')),
                ('target_desc', models.TextField(blank=True, null=True, verbose_name='지원대상')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='상품상세URL')),
                ('is_active', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '금융 상품',
                'verbose_name_plural': '금융 상품 목록',
            },
        ),
        migrations.CreateModel(
            name='HousingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manage_no', models.CharField(max_length=50, unique=True, verbose_name='주택관리번호')),
                ('pblanc_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='공고번호')),
                ('title', models.CharField(max_length=255, verbose_name='주택명')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='주택구분')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='공급지역')),
                ('location', models.TextField(blank=True, null=True, verbose_name='공급위치')),
                ('notice_date', models.DateField(blank=True, null=True, verbose_name='모집공고일')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='접수시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='접수종료일')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='공고상세URL')),
                ('org', models.CharField(blank=True, max_length=100, null=True, verbose_name='시행/시공사')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성상태')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='전체원본데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '주거 상품',
                'verbose_name_plural': '주거 상품 목록',
                'ordering': ['-notice_date'],
            },
        ),
        migrations.CreateModel(
            name='WelfareProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=100, unique=True, verbose_name='정책ID')),
                ('title', models.CharField(max_length=255, verbose_name='정책명')),
                ('org_nm', models.CharField(max_length=100, verbose_name='주관기관')),
                ('benefit_desc', models.TextField(verbose_name='지원내용')),
                ('target_desc', models.TextField(verbose_name='지원대상')),
                ('age_limit', models.CharField(blank=True, max_length=100, null=True, verbose_name='연령제한')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='상세URL')),
                ('is_active', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '복지 상품',
                'verbose_name_plural': '복지 상품 목록',
            },
        ),
    ]
