# Generated by Django 6.0.3 on 2026-04-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_road', '0003_financeproduct_housingproduct_welfareproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingMarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='지역 (예: 서울, 강남구 등)', max_length=100)),
                ('complex_name', models.CharField(help_text='단지명/상품명', max_length=200)),
                ('category', models.CharField(blank=True, help_text='분류 (민영, 공공 등)', max_length=50, null=True)),
                ('avg_competition_rate', models.FloatField(default=0.0, help_text='평균 경쟁률')),
                ('avg_winner_score', models.FloatField(default=0.0, help_text='평균 당첨 가점')),
                ('avg_winner_age', models.FloatField(default=0.0, help_text='평균 당첨자 연령')),
                ('sales_price', models.BigIntegerField(default=0, help_text='분양가/실거래가 (원)')),
                ('price_per_meter', models.BigIntegerField(default=0, help_text='제곱미터당 단가')),
                ('data_year', models.IntegerField(default=2024, help_text='데이터 기준 연도')),
                ('raw_data', models.JSONField(default=dict, help_text='원본 행 전체 데이터')),
                ('source', models.CharField(blank=True, help_text='출처 (예: data.go.kr)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '주거 시장 데이터',
                'verbose_name_plural': '주거 시장 데이터 목록',
            },
        ),
    ]
