# Generated by Django 6.0.3 on 2026-04-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_road', '0004_housingmarketdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='welfareproduct',
            name='category',
            field=models.CharField(default='복지정책', max_length=100, verbose_name='정책구분'),
        ),
        migrations.AddField(
            model_name='welfareproduct',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='지원지역'),
        ),
        migrations.AlterField(
            model_name='financeproduct',
            name='category',
            field=models.CharField(default='대출', max_length=100, verbose_name='상품구분'),
        ),
        migrations.AlterField(
            model_name='financeproduct',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='상세URL'),
        ),
        migrations.AlterField(
            model_name='housingmarketdata',
            name='avg_competition_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='housingmarketdata',
            name='avg_winner_age',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='housingmarketdata',
            name='avg_winner_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='housingmarketdata',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='housingmarketdata',
            name='complex_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='housingmarketdata',
            name='data_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='housingmarketdata',
            name='price_per_meter',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='housingmarketdata',
            name='raw_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='housingmarketdata',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='housingmarketdata',
            name='sales_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='housingmarketdata',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='housingproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='housingproduct',
            name='manage_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='주택관리번호'),
        ),
        migrations.AlterField(
            model_name='housingproduct',
            name='pblanc_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='공고번호'),
        ),
        migrations.AlterField(
            model_name='housingproduct',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
