# Generated by Django 6.0.3 on 2026-04-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_road', '0005_welfareproduct_category_welfareproduct_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='welfareproduct',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='종료일'),
        ),
        migrations.AddField(
            model_name='welfareproduct',
            name='notice_date',
            field=models.DateField(blank=True, null=True, verbose_name='공고일'),
        ),
    ]
