# Generated by Django 6.0.3 on 2026-04-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_road', '0006_welfareproduct_end_date_welfareproduct_notice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeproduct',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='종료일'),
        ),
        migrations.AddField(
            model_name='financeproduct',
            name='notice_date',
            field=models.DateField(blank=True, null=True, verbose_name='공고일'),
        ),
    ]
