# Generated by Django 6.0.3 on 2026-04-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_road', '0007_financeproduct_end_date_financeproduct_notice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiagnostic',
            name='homeless_years',
            field=models.IntegerField(default=0, help_text='무주택 기간이 0~15년(이상) 중 해당되는 기간', verbose_name='무주택 기간 (년)'),
        ),
        migrations.AddField(
            model_name='userdiagnostic',
            name='is_first_home',
            field=models.BooleanField(default=True, help_text='태어나서 지금까지 집을 소유한 적이 없는 경우', verbose_name='생애최초 주택구입 여부'),
        ),
        migrations.AddField(
            model_name='userdiagnostic',
            name='is_homeless',
            field=models.BooleanField(default=True, help_text='현재 본인 및 세대원 전원이 무주택인 경우', verbose_name='현재 무주택 여부'),
        ),
    ]
