# Generated by Django 6.0.3 on 2026-04-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_road', '0008_userdiagnostic_homeless_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingproduct',
            name='sales_price',
            field=models.IntegerField(default=0, help_text='단위: 만원 (분양가 또는 매매 시세)', verbose_name='주택 가격'),
        ),
        migrations.AlterField(
            model_name='housingproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 여부'),
        ),
        migrations.AlterField(
            model_name='housingproduct',
            name='org',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='주관 기관'),
        ),
    ]
