# Generated by Django 6.0.3 on 2026-04-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_road', '0009_housingproduct_sales_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welfareproduct',
            name='benefit_desc',
            field=models.TextField(blank=True, null=True, verbose_name='지원내용'),
        ),
        migrations.AlterField(
            model_name='welfareproduct',
            name='target_desc',
            field=models.TextField(blank=True, null=True, verbose_name='지원대상'),
        ),
    ]
