# Generated by Django 6.0.3 on 2026-04-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_road', '0010_alter_welfareproduct_benefit_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiagnostic',
            name='region',
            field=models.CharField(choices=[('Seoul', '서울'), ('Gyeonggi', '경기'), ('Incheon', '인천'), ('Busan', '부산'), ('Daegu', '대구'), ('Gwangju', '광주'), ('Daejeon', '대전'), ('Ulsan', '울산'), ('Sejong', '세종'), ('Gangwon', '강원'), ('Chungbuk', '충북'), ('Chungnam', '충남'), ('Jeonbuk', '전북'), ('Jeonnam', '전남'), ('Gyeongbuk', '경북'), ('Gyeongnam', '경남'), ('Jeju', '제주'), ('Other', '기타')], default='Seoul', max_length=20, verbose_name='거주지'),
        ),
    ]
